name: Project CI

on:   
  push:
    branches:
    - main

jobs:
  project-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 2023-amse-template
    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies

    # Run Code Format check

    # Run tests 
    - name: Tests with pytest
      run: |
        /project/testing.sh