name: Project CI

on:   
  push:
    branches:
    - main

env: 
  APIKey: ${{ secrets.APIKey }}
  ClientID: ${{ secrets.ClientID }}

jobs:
  project-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies
    - name: Install dependecies
      run: |
        pip install pytest
        pip install pandas
        pip install pysqlite3
        pip install python-dotenv
        pip install requests
        pip install sqlalchemy
        

    # Run Code Format check

    # Run tests 
    - name: Tests with pytest
      run: |
        ./project/testing.sh